### ISSUE TITLE
福昕阅读器中不能使用

### ISSUE THREAD

**Issue by zxyacg** [Borber/Tran#103]
弹不出来翻译框

**Comment by Borber** [comment]
测试一下能否 ctrl + c 复制文本?

**Comment by zxyacg** [comment]
> 测试一下能否 ctrl + c 复制文本?

可以复制

**Comment by Borber** [comment]
> > 测试一下能否 ctrl + c 复制文本?
> 
> 可以复制

那没道理啊, 我去下载一个试试

**Comment by Borber** [comment]
是的, 福昕阅读器 好像对于 Ctrl + C 有点特殊处理, 你可以注意到右下角会闪一个窗口, 这破坏了 Tran 的取词, 所以确实无法使用

**Comment by zxyacg** [comment]
> 是的, 福昕阅读器 好像对于 Ctrl + C 有点特殊处理, 你可以注意到右下角会闪一个窗口, 这破坏了 Tran 的取词, 所以确实无法使用

有办法解决吗？佬

**Comment by Borber** [comment]
> > 是的, 福昕阅读器 好像对于 Ctrl + C 有点特殊处理, 你可以注意到右下角会闪一个窗口, 这破坏了 Tran 的取词, 所以确实无法使用
> 
> 有办法解决吗？佬

无法解决, 抱歉, 因为只能通过 Ctrl + C 来进行取词

**Comment by Borber** [comment]
已添加到 已知 issue. 没办法你试试别的翻译软件吧  https://github.com/pot-app/pot-desktop pot也很优秀的

**Comment by Borber** [comment]
福昕阅读器可以使用了， 请尝试 0.2.9 版本
