### ISSUE TITLE
0.2.7 版本被 windows defender报毒

### ISSUE THREAD

**Issue by XIYU11864** [Borber/Tran#106]
![image](https://github.com/Borber/Tran/assets/75518225/78a80459-2c67-4be4-ba19-aabc98ee1d77)

**Comment by Borber** [comment]
可能是因为添加了开机启动导致的( 请信任 🤣

**Comment by Borber** [comment]
开机自启这块确实是考虑不周了, 我调整一下去掉, 然后重发一下 0.2.7 吧
