### ISSUE TITLE
0.2.8: mac m1 文件已损坏

### ISSUE THREAD

**Issue by mdddj** [Borber/Tran#125]
<img width="260" alt="image" src="https://github.com/Borber/Tran/assets/29020213/84d1198d-91d7-4b27-b0a3-ebd5d6c3791f">

**Comment by Borber** [comment]
> <img alt="image" width="260" src="https://private-user-images.githubusercontent.com/29020213/313569439-84d1198d-91d7-4b27-b0a3-ebd5d6c3791f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDM0NzksIm5iZiI6MTcxMDc0MzE3OSwicGF0aCI6Ii8yOTAyMDIxMy8zMTM1Njk0MzktODRkMTE5OGQtOTFkNy00YjI3LWIwYTMtZWJkNWQ2YzM3OTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA2MjYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5YTllMzAwOGY2Yjg3NDMyOTY0YTU3Mjk2ZDExMTI0MjA0Y2Y4NWUxOTRhNmVlMDlhOTg3OTAxMDNiNzAzOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nCw3ylDVrv7pJb6la6n080paq1J1qz0Q1neC4HcUMU8">

斯。。。 我手上没有 mac 好像没法修耶。。 你试试彻底删除 之前的旧版本？

**Comment by mdddj** [comment]
大佬,我这第一次装

**Comment by Borber** [comment]
Troubleshooting

由于应用没有签名，所以 MacOS 可能会显示开发者无法验证或应用已损坏

点击 取消 按钮，然后去 设置 -> 隐私与安全性 页面，点击 仍要打开 按钮，然后在弹出窗口里点击

打开 按钮即可，以后打开 pot 就再也不会有任何弹窗警告了

如果在 隐私与安全性 中找不到以上选项，或启动时提示文件损坏。打开 Terminal.app，并输入以下命令，然后重启 pot 即可：

bash
sudo xattr -d com.apple.quarantine /Applications/Tran.app

试试

**Comment by mdddj** [comment]
大佬,可以打开了,但是按什么快捷键翻译啊,alt+x没反应

**Comment by Borber** [comment]
> 大佬,可以打开了,但是按什么快捷键翻译啊,alt+x没反应

双击 CapsLock
