### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by WHMyyds** [Borber/Tran#127]
1.在Windows端，是否考虑添加uwp应用？有时候uwp要比程序方便。
2.我觉得可以再做一个多语言互译版本，给有需求的人~~比如我~~用

**Comment by Borber** [comment]
> 1.在Windows端，是否考虑添加uwp应用？有时候uwp要比程序方便。 2.我觉得可以再做一个多语言互译版本，给有需求的人~比如我~用

uwp那就是仅翻译了，没法做到划词触发，窗口操作这些， 你可以尝试直接用翻译接口写一个。 如果是uwp的话我其实更推荐  https://api.deeplx.org/  这个接口。
