### ISSUE TITLE
怎么是大写汉字

### ISSUE THREAD

**Issue by jsasg** [Borber/Tran#133]

**Comment by Borber** [comment]
截图我看看，应该不会，我一直使用的都是简体， 以及你用的版本是哪个？

**Comment by jsasg** [comment]
![QQ截图20240321111536](https://github.com/Borber/Tran/assets/14173974/774bfb28-d610-4b47-83d0-0e0d136bac6e)
而且有时只有日语，没有汉字...........

**Comment by jsasg** [comment]
貌似就是日语，不是汉字

**Comment by Borber** [comment]
![image](https://github.com/Borber/Tran/assets/30563826/edfd7868-ec5c-48fb-88c4-490bc32bded0)
中文用户阅读英文用这个版本哈，你应该是下成了 中日用户的版本

**Comment by jsasg** [comment]
貌似是下错版本了，谢谢.
