### ISSUE TITLE
replace the verion number v.0.2.8 to v0.2.8 or 0.2.8

### ISSUE THREAD

**Issue by Kiri2002** [Borber/Tran#140]
v.0.2.8 just looks wired, 
most project using v0.2.8.

**Comment by Borber** [comment]
> v.0.2.8 just looks wired, most project using v0.2.8.

I made some mistakes when I wrote the script before. Then it continued. Will I modify it in 0.2.9 be ok?

**Comment by Kiri2002** [comment]
> > v.0.2.8 just looks wired, most project using v0.2.8.
> 
> I made some mistakes when I wrote the script before. Then it continued. Will I modify it in 0.2.9 be ok?

that will be great!

**Comment by Borber** [comment]
already edited
