### ISSUE TITLE
request build command

### ISSUE THREAD

**Issue by Kiri2002** [Borber/Tran#141]
Hi, I'm trying build this project locally, struggling by lacking of information of how to build, could you give some build information?
Thank you for such a beautiful soft. Best wishes!

**Comment by Borber** [comment]
certainly.

1. First you must meet the requirements of tauri:  https://tauri.app/v1/guides/getting-started/prerequisites
2. `Tran` uses `pnpm` as the package manager, so you need to install a relatively new node (I am using v20.11.1), and enable corepack to use pnpm. Generally speaking, just run `corepack enable` can be completed after installing the node.
3. Install front-end dependencies in tran dir with `pnpm install`
4. Compile `pnpm tauri build`

**Comment by Borber** [comment]
If you still encounter any compilation problems, you can ask directly and I will be happy to assist.
