### ISSUE TITLE
deepl 引擎

### ISSUE THREAD

**Issue by amdoi7** [Borber/Tran#148]
能否可以自定义 翻译引擎 (比如 deepl  的api来使用

**Comment by Borber** [comment]
deepl的api太慢了, 而且, deepl 目前测试下来没比google好太多,有时候甚至更蠢

**Comment by amdoi7** [comment]
> deepl的api太慢了, 而且, deepl 目前测试下来没比google好太多,有时候甚至更蠢

如果是论文 这种比较长一点的英语段落 deepl 还是有点优势 这种场景下速度也不是什么很重要的问点

**Comment by Borber** [comment]
和 #216  一致, 不考虑多翻译源
