### ISSUE TITLE
能不能改成快捷键可配置啊？Shift快捷键确实被占用了

### ISSUE THREAD

**Issue by l-ff** [Borber/Tran#161]

**Comment by Borber** [comment]
选择 shift 属实是无奈之举， tauri 的快捷键绑定 linux 有问题， 单纯按键监听只能选修饰键， capslock 又在终端上会导致选择区域刷新， 最后只能选shift了， （ 或者 ctrl？

**Comment by cliouo** [comment]
是否可以改为和Mode选择镜像或直连一样，给几个常用可选项?，`capslock`、`shift`、`ctrl`、`alt`都是双击。

---------------------

<sub>更或者，现在已经打25个包了，那如果能实现自定义构建自己的小而美，like this https://openwrt.ai/ 自定义构建固件<sub/>
<sub>最终还是小而美，但10个人有10个人自己的小而美?<sub/>
<sub>如果以后真的有时间的话<sub/>

**Comment by Borber** [comment]
> 是否可以改为和Mode选择镜像或直连一样，给几个常用可选项?，`capslock`、`shift`、`ctrl`、`alt`都是双击。
> 
> 更或者，现在已经打25个包了，那如果能实现自定义构建自己的小而美，like this https://openwrt.ai/ 自定义构建固件 最终还是小而美，但10个人有10个人自己的小而美? 如果以后真的有时间的话

alt 应该不太行， 大部分时间都会调出菜单栏， capslock， shift， ctrl 可选这个可以做到。

自定义构建固件有一个缺点就是需要等待。 除非我加上缓存这块， 可以考虑， 因为后面官网还需要改进，有考虑更人性化的选择方式，

**Comment by Borber** [comment]
https://github.com/Borber/Tran/releases/tag/v0.2.14  快捷键选择 已添加
![image](https://github.com/Borber/Tran/assets/30563826/30f8280a-e7b6-43e2-a357-7a7ab58172e2)
