### ISSUE TITLE
能否支持自定义百度，腾讯API翻译接口

### ISSUE THREAD

**Issue by whywayne2020** [Borber/Tran#216]
国内百度，腾讯等API翻译速度更快，请作者考虑。

**Comment by Borber** [comment]
![image](https://github.com/Borber/Tran/assets/30563826/9321cb7f-4556-4dcf-9e85-a7788e42f541)

抱歉, 没有支持多翻译接口的计划, 谷歌的翻译已经够优秀了, 我综合考虑下来体验最好的就是他了, 而且没有使用限制, 用户不必进行配置, 也不用担心额度的问题

**Comment by whywayne2020** [comment]
谢谢！这个软件简单实用，体验非常好。我感觉百度和腾讯接口翻译速度要快一些。期待一下下一版浅色light主题。

**Comment by Borber** [comment]
> 谢谢！这个软件简单实用，体验非常好。我感觉百度和腾讯接口翻译速度要快一些。期待一下下一版浅色light主题。

已支持 浅色主题, https://github.com/Borber/Tran/releases/tag/v0.2.15
