### ISSUE TITLE
翻页问题

### ISSUE THREAD

**Issue by WHMyyds** [Borber/Tran#241]
在划词翻译大量句子时，翻页总会多翻一行到半行，导致我看不到翻译

**Comment by Borber** [comment]
你好, 可以提供更详细的说明或者截图吗?

**Comment by WHMyyds** [comment]
![第一页](https://github.com/Borber/Tran/assets/123004192/12058e8c-ceb1-408e-8d23-89ede6a3637b)
![翻页后](https://github.com/Borber/Tran/assets/123004192/1af78840-70de-4e43-98dd-b2a896e06055)
大佬，看看图片，能明白不~

**Comment by WHMyyds** [comment]
最后一行有遮挡

**Comment by WHMyyds** [comment]
语文不好😄

**Comment by Borber** [comment]
收到, 我今晚回去看一下

**Comment by WHMyyds** [comment]
❤

**Comment by nanbeiduoqilu** [comment]
类似的需求我在tg群组也反馈过，就是翻译文字过多的时候，翻页会跳过一行到半行内容~

**Comment by Borber** [comment]
0.2.16 已修复 请查看

**Comment by WHMyyds** [comment]
感谢，大佬辛苦啦！👍
