### ISSUE TITLE
mac 上 系统托盘位置错位

### ISSUE THREAD

**Issue by lemos1235** [Borber/tran#31]

**Comment by Borber** [comment]
> _No description provided._

可以提供截图吗? 是偏向了哪边?

**Comment by lemos1235** [comment]
大概是中间靠左的位置

<img width="1913" alt="image" src="https://github.com/Borber/tran/assets/23135552/62760fb1-4526-4ae0-b687-08a0d01ecffe">

**Comment by Borber** [comment]
> 大概是中间靠左的位置
> 
> <img alt="image" width="1913" src="https://private-user-images.githubusercontent.com/23135552/292631198-62760fb1-4526-4ae0-b687-08a0d01ecffe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNTQ5MjcsIm5iZiI6MTcwMzM1NDYyNywicGF0aCI6Ii8yMzEzNTU1Mi8yOTI2MzExOTgtNjI3NjBmYjEtNDUyNi00YWUwLWI2ODctMDhhMGQwMWVjZmZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDE4MDM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1YzlhZTMyY2JlYjJkMWMxMTFhZDhmNmU2MGU4MjIzNjhkYTIzZjg4Yzc3MjNiMzIwNWIxMWQyZmE5YzhkZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-6fGQhjQ79dJPjLmmovx5sbIdxqjuNjkct2bkNX8lsI">

收到, 但我应该比较难解决这个问题(没法调试看到效果), 我在求助其他使用mac的大佬了.  抱歉请等待后续推进

**Comment by Borber** [comment]
https://github.com/Borber/tran/releases/tag/v.0.1.9  请尝试一下这个版本 应该以及完全修复了 tray 和 panel 的问题

**Comment by Borber** [comment]
你好, 请问问题解决了吗, 如果没问题我就colse这个issue了
