### ISSUE TITLE
Failed to register global shortcut: GlobalShortcut(InvalidAccelerator("Unable to register global shortcut"))

### ISSUE THREAD

**Issue by asukaminato0721** [Borber/Tran#34]
log

```sh
✖  RUST_BACKTRACE=full tran
thread 'main' panicked at src/setup.rs:19:10:
Failed to register global shortcut: GlobalShortcut(InvalidAccelerator("Unable to register global shortcut"))
stack backtrace:
   0:     0x557b625290e9 - <unknown>
   1:     0x557b623b6f70 - <unknown>
   2:     0x557b624f93fe - <unknown>
   3:     0x557b6252aa2e - <unknown>
   4:     0x557b6252a345 - <unknown>
   5:     0x557b6252b24e - <unknown>
   6:     0x557b6252ad90 - <unknown>
   7:     0x557b6252ace6 - <unknown>
   8:     0x557b6252acdf - <unknown>
   9:     0x557b622dff94 - <unknown>
  10:     0x557b622e0502 - <unknown>
  11:     0x557b62327ea7 - <unknown>
  12:     0x557b62340535 - <unknown>
  13:     0x557b6237799b - <unknown>
  14:     0x557b62374a7c - <unknown>
  15:     0x557b62320d32 - <unknown>
  16:     0x557b6237a059 - <unknown>
  17:     0x7fa7dc845cd0 - <unknown>
  18:     0x7fa7dc845d8a - __libc_start_main
  19:     0x557b622f1b15 - <unknown>
  20:                0x0 - <unknown>
Gtk-Message: 00:37:01.630: Failed to load module "appmenu-gtk-module"
fish: Job 1, 'RUST_BACKTRACE=full tran' terminated by signal SIGABRT (Abort)
```

**Comment by asukaminato0721** [comment]
PKGBUILD

```sh
pkgname=tran-bin
pkgver=0.1.10
pkgrel=1
pkgdesc="简洁, 快速, 划词翻译"
arch=(x86_64)
url="https://github.com/Borber/tran"
license=('GPL3')
depends=(gtk3
	webkit2gtk
	glib2
	gcc-libs
	cairo
	gdk-pixbuf2
	glibc
	openssl
	hicolor-icon-theme
	libsoup
)
provides=(tran)
source=("https://github.com/Borber/tran/releases/download/v.${pkgver}/tran_zh_en_${pkgver}_amd64.deb"
)
sha256sums=('6d9ef7530382921f2ca88532165d9ba181b576482fe23599d352ef6f8a934e40')

package() {
	tar -xf data.tar.* -C $pkgdir
}
```

**Comment by Borber** [comment]
是wayland吗？ 好像tauri在wayland上的快捷键注册确实还有问题 类似参考： https://github.com/pot-app/pot-desktop/issues/12

**Comment by Borber** [comment]
另一个参考 https://github.com/tauri-apps/tauri/issues/3578

**Comment by asukaminato0721** [comment]
```
✖  RUST_BACKTRACE=full GDK_BACKEND=x11 tran
Gtk-Message: 00:57:42.943: Failed to load module "appmenu-gtk-module"
Gtk-Message: 00:57:43.167: Failed to load module "appmenu-gtk-module"
Asset `panel` not found; fallback to panel.html
```

没有出现窗口

**Comment by Borber** [comment]
或者点击托盘图标试试

**Comment by asukaminato0721** [comment]
> 划一段文字， 然后按 Alt + X
> 或者点击托盘图标试试

很神奇, 没有托盘. alt + x 也没效果.

然后经测试, 加个 sudo 可以出托盘图标. 但是 alt + x 没有效果.

**Comment by Borber** [comment]
> > 划一段文字， 然后按 Alt + X
> > 或者点击托盘图标试试
> 
> 很神奇, 没有托盘. alt + x 也没效果.
> 
> 然后经测试, 加个 sudo 可以出托盘图标. 但是 alt + x 没有效果.

我傻傻了， 应该不用sudo的呀， 托盘能点出设置界面吗？ 快捷键可能还是没绑上

**Comment by asukaminato0721** [comment]
>  托盘能点出设置界面吗？

不能

**Comment by Borber** [comment]
> > 托盘能点出设置界面吗？
> 
> 不能

😥

**Comment by Borber** [comment]
> > 托盘能点出设置界面吗？
> 
> 不能

佬，你看看是不是和这个同病相怜了 https://github.com/pot-app/pot-desktop?tab=readme-ov-file#archmanjaro

**Comment by asukaminato0721** [comment]
可是我没有 n 卡啊...

而且试过 appimage 版也打不开

**Comment by Borber** [comment]
> 可是我没有 n 卡啊...
> 
> 而且试过 appimage 版也打不开

我再去找找可能的原因😥

**Comment by Borber** [comment]
大佬, 快捷键模块已经被我移除了, 现在再尝试一下吗? 🥰

**Comment by asukaminato0721** [comment]
![image](https://github.com/Borber/Tran/assets/30024051/a3e220f1-dfb0-4cf7-8f63-b679f0f73717)

```
GDK_BACKEND=x11 tran
```

works

**Comment by asukaminato0721** [comment]
发现有很多个变种，所以不确定应该打哪个，或者就类似

https://aur.archlinux.org/packages?O=0&SeB=nd&K=thunderbird-beta-i18n&outdated=&SB=p&SO=d&PP=50&submit=Go 这样，但是太恐怖了。

问题就留给上游想了，pkgbuild 在下面，已测试通过。

```sh
# Contributor: asuka minato <i at asukaminato dot eu dot org>
pkgname=tran-bin
pkgver=0.2.1
pkgrel=1
pkgdesc="简洁, 快速, 划词翻译"
arch=(x86_64)
url="https://github.com/Borber/tran"
license=('GPL3') # todo
depends=(gtk3
	webkit2gtk-4.1
	glib2
	gcc-libs
	cairo
	gdk-pixbuf2
	glibc
	openssl
	hicolor-icon-theme
	libx11
	libxtst
	libsoup3
)
provides=(tran)
source=("https://github.com/Borber/tran/releases/download/v.${pkgver}/tran_zh_en_${pkgver}_amd64.deb"
)
sha256sums=('daff3f3c4412660ef9966f0d802a3732a776699160a8f60404d460dd723da90d')

package() {
	tar -xf data.tar.* -C $pkgdir
	find $pkgdir -name "*.desktop" -print -exec sed -i -r 's/Exec=.*/Exec=env GDK_BACKEND=x11 tran/' {} \;
}
```

**Comment by Borber** [comment]
> 发现有很多个变种，所以不确定应该打哪个，或者就类似
> 
> https://aur.archlinux.org/packages?O=0&SeB=nd&K=thunderbird-beta-i18n&outdated=&SB=p&SO=d&PP=50&submit=Go 这样，但是太恐怖了。
> 
> 问题就留给上游想了，pkgbuild 在下面，已测试通过。
> 
> ```shell
> # Contributor: asuka minato <i at asukaminato dot eu dot org>
> pkgname=tran-bin
> pkgver=0.2.1
> pkgrel=1
> pkgdesc="简洁, 快速, 划词翻译"
> arch=(x86_64)
> url="https://github.com/Borber/tran"
> license=('GPL3') # todo
> depends=(gtk3
> 	webkit2gtk-4.1
> 	glib2
> 	gcc-libs
> 	cairo
> 	gdk-pixbuf2
> 	glibc
> 	openssl
> 	hicolor-icon-theme
> 	libx11
> 	libxtst
> 	libsoup3
> )
> provides=(tran)
> source=("https://github.com/Borber/tran/releases/download/v.${pkgver}/tran_zh_en_${pkgver}_amd64.deb"
> )
> sha256sums=('daff3f3c4412660ef9966f0d802a3732a776699160a8f60404d460dd723da90d')
> 
> package() {
> 	tar -xf data.tar.* -C $pkgdir
> 	find $pkgdir -name "*.desktop" -print -exec sed -i -r 's/Exec=.*/Exec=env GDK_BACKEND=x11 tran/' {} \;
> }
> ```

吼吼吼, 其实可能更加恐怖 甚至是它的平方的数量级, 虽然目前就只有三个, 不过这样已经很好啦, 感谢大佬
