### ISSUE TITLE
这个没法跟autohotkey一起使用，只要启动autohotkey这个就不生效了

### ISSUE THREAD

**Issue by pizixi** [Borber/Tran#407]

**Comment by Borber** [comment]
没有用过 autohotkey 耶, 他是绑定了什么还是 监控键盘之类的?

**Comment by pizixi** [comment]
> 没有用过 autohotkey 耶, 他是绑定了什么还是 监控键盘之类的?

autohotkey 没有绑定这些快捷键，autohotkey 我用的挺多的，改建，快捷输入等等，不知道有没有办法能解决，请问这个不能设置组合键吗？

**Comment by Borber** [comment]
> > 没有用过 autohotkey 耶, 他是绑定了什么还是 监控键盘之类的?
> 
> autohotkey 没有绑定这些快捷键，autohotkey 我用的挺多的，改建，快捷输入等等，不知道有没有办法能解决，请问这个不能设置组合键吗？

可以的, 你看看菜单里的快捷键选择

**Comment by pizixi** [comment]
我看目前只能 双击Shift 双击Ctrl 或者  双击Caps，我说的是比如按win+` 键这样的组合键
