### ISSUE TITLE
自定义快捷键和输入翻译

### ISSUE THREAD

**Issue by jlduu** [Borber/Tran#54]
1. 默认alt+x和电脑一些软件的快捷键冲突
2. 有时候需要输入中文翻译为英文

**Comment by Borber** [comment]
1. 快捷键冲突这个目前有点难解决是因为目前的windows的获取 “选择文本" 的方式是，按下快捷键之后模拟抬起快捷键（至少抬起功能键）然后锁定剪贴板，模拟 `Ctrl + C` 复制文本，获取剪贴板文本。 

    -  我对 `Alt + X` 做了相关优化。 但我目前没法对其他自定义的按键进行优化，或者你可以建议一个新的快捷键，我可以考虑添加进来做独立的优化。
    -  其他软件的冲突是 Tran 导致软件的功能无法使用还是软件的导致 Tran无法使用呢?

2. 输入中文翻译英文我目前的操作是先输入中文，然后划词翻译，划过复制，黏贴回来。考察过其他软件的翻译面板， 总感觉这个功能做不到十分简洁。

**Comment by jlduu** [comment]
> 1. 快捷键冲突这个目前有点难解决是因为目前的windows的获取 “选择文本" 的方式是，按下快捷键之后模拟抬起快捷键（至少抬起功能键）然后锁定剪贴板，模拟 `Ctrl + C` 复制文本，获取剪贴板文本。
>    
>    * 我对 `Alt + X` 做了相关优化。 但我目前没法对其他自定义的按键进行优化，或者你可以建议一个新的快捷键，我可以考虑添加进来做独立的优化。
>    * 其他软件的冲突是 Tran 导致软件的功能无法使用还是软件的导致 Tran无法使用呢?
> 2. 输入中文翻译英文我目前的操作是先输入中文，然后划词翻译，划过复制，黏贴回来。考察过其他软件的翻译面板， 总感觉这个功能做不到十分简洁。

感谢解答，我用SumatraPDF看文献的时候，按下alt+x会先调用SumatraPDF的快捷方式，然后再快速按就会调用Tran的翻译

**Comment by Borber** [comment]
> > 1. 快捷键冲突这个目前有点难解决是因为目前的windows的获取 “选择文本" 的方式是，按下快捷键之后模拟抬起快捷键（至少抬起功能键）然后锁定剪贴板，模拟 `Ctrl + C` 复制文本，获取剪贴板文本。
> >    
> >    * 我对 `Alt + X` 做了相关优化。 但我目前没法对其他自定义的按键进行优化，或者你可以建议一个新的快捷键，我可以考虑添加进来做独立的优化。
> >    * 其他软件的冲突是 Tran 导致软件的功能无法使用还是软件的导致 Tran无法使用呢?
> > 2. 输入中文翻译英文我目前的操作是先输入中文，然后划词翻译，划过复制，黏贴回来。考察过其他软件的翻译面板， 总感觉这个功能做不到十分简洁。
> 
> 感谢解答，我用SumatraPDF看文献的时候，按下alt+x会先调用SumatraPDF的快捷键功能，然后再快速按就会调用Tran的翻译

我试了一下，发现是  SumatraPDF 捕获了 Alt，然后打开了菜单， 目前折衷的办法是，先按一下 Alt 再使用 Alt + X 快捷键

**Comment by jlduu** [comment]
> > > 1. 快捷键冲突这个目前有点难解决是因为目前的windows的获取 “选择文本" 的方式是，按下快捷键之后模拟抬起快捷键（至少抬起功能键）然后锁定剪贴板，模拟 `Ctrl + C` 复制文本，获取剪贴板文本。
> > >    
> > >    * 我对 `Alt + X` 做了相关优化。 但我目前没法对其他自定义的按键进行优化，或者你可以建议一个新的快捷键，我可以考虑添加进来做独立的优化。
> > >    * 其他软件的冲突是 Tran 导致软件的功能无法使用还是软件的导致 Tran无法使用呢?
> > > 2. 输入中文翻译英文我目前的操作是先输入中文，然后划词翻译，划过复制，黏贴回来。考察过其他软件的翻译面板， 总感觉这个功能做不到十分简洁。
> > 
> > 
> > 感谢解答，我用SumatraPDF看文献的时候，按下alt+x会先调用SumatraPDF的快捷键功能，然后再快速按就会调用Tran的翻译
> 
> 我试了一下，发现是 SumatraPDF 捕获了 Alt，然后打开了菜单， 目前折衷的办法是，先按一下 Alt 再使用 Alt + X 快捷键， 这样的话就不用快速按两次了，

试了一下，确实是这样，非常感谢🙇‍

**Comment by Borber** [comment]
> > > > 1. 快捷键冲突这个目前有点难解决是因为目前的windows的获取 “选择文本" 的方式是，按下快捷键之后模拟抬起快捷键（至少抬起功能键）然后锁定剪贴板，模拟 `Ctrl + C` 复制文本，获取剪贴板文本。
> > > >    
> > > >    * 我对 `Alt + X` 做了相关优化。 但我目前没法对其他自定义的按键进行优化，或者你可以建议一个新的快捷键，我可以考虑添加进来做独立的优化。
> > > >    * 其他软件的冲突是 Tran 导致软件的功能无法使用还是软件的导致 Tran无法使用呢?
> > > > 2. 输入中文翻译英文我目前的操作是先输入中文，然后划词翻译，划过复制，黏贴回来。考察过其他软件的翻译面板， 总感觉这个功能做不到十分简洁。
> > > 
> > > 
> > > 感谢解答，我用SumatraPDF看文献的时候，按下alt+x会先调用SumatraPDF的快捷键功能，然后再快速按就会调用Tran的翻译
> > 
> > 
> > 我试了一下，发现是 SumatraPDF 捕获了 Alt，然后打开了菜单， 目前折衷的办法是，先按一下 Alt 再使用 Alt + X 快捷键， 这样的话就不用快速按两次了，
> 
> 试了一下，确实是这样，非常感谢🙇‍

哈哈哈，不客气。 哎，选快捷键真的太难了，要么不好按，要么会和常用的冲突。比如有考虑双击`Caps` (大写锁定键) 来弹出，但是也有别的老牌软件使用了这个，也有点怕冲突

**Comment by Borber** [comment]
@jlduu  以及如果可以的话拜托帮忙宣传一下 🤝

> # 积极使用
> 理论上，更多人使用则 `tran` 翻译速度会保持在很快的速度，因为 `vercel` 冷启动耗时很长。频繁的请求能使它一直运行。所以鼓励您频繁使用 `tran`. 同理也拜托您推广 `tran`

**Comment by tiankongchuan** [comment]
时常要挂着代理工作，挂着日本节点翻译返回回来就会是日文

**Comment by Borber** [comment]
v.0.1.12 更改为 双击 `CapsLock` 为快捷键了,  理论上只要没有安装其他利用 `CapsLock` 的软件, 所有别的软件 如 ppt 系统编辑器,之类的 都不会再产生冲突了

以及, 速度也更快了

**Comment by Borber** [comment]
https://github.com/Borber/Tran/releases/tag/v0.2.14  快捷键选择 已添加
![image](https://github.com/Borber/Tran/assets/30563826/30f8280a-e7b6-43e2-a357-7a7ab58172e2)
