### ISSUE TITLE
挂代理会返回非中文

### ISSUE THREAD

**Issue by tiankongchuan** [Borber/Tran#61]
时常要挂着代理工作，挂着日本节点翻译返回回来就会是日文，这点还是挺麻烦的

**Comment by Borber** [comment]
> 时常要挂着代理工作，挂着日本节点翻译返回回来就会是日文，这点还是挺麻烦的

你用的是哪个编译版本? 给我一下名称, 以及 截图一下问题界面 😁

**Comment by tiankongchuan** [comment]
Tran 0.1.11 不是问题界面，就是挂代理，然后选镜像，返回回来的就是日语

**Comment by Borber** [comment]
> Tran 0.1.11 不是问题界面，就是挂代理，然后选镜像，返回回来的就是日语

![image](https://github.com/Borber/Tran/assets/30563826/05f86416-97c0-4455-bee1-c193d66faa1a)
我担心你xuan选错了版本，

**Comment by Borber** [comment]
如果是 中-英 用户 请选择 zh_en , 而且默认不会走代理, 走的是镜像转发过去的, 应该不会影响到结果

**Comment by tiankongchuan** [comment]
抱歉确实是我下错了版本，刚好挂着日本节点返回的日语让我误以为是代理的问题

**Comment by Borber** [comment]
好哒， 问题解决了就好
