### ISSUE TITLE
可以在界面上添加一个版本号的显示

### ISSUE THREAD

**Issue by FWiiii** [Borber/Tran#66]
1. 更新频率还挺高的，但是不太好看自己现在用的是什么版本，可以在界面左下角加一个版本号
2. 还可以试试加一个updater

**Comment by Borber** [comment]
> 1. 更新频率还挺高的，但是不太好看自己现在用的是什么版本，可以在界面左下角加一个版本号
> 2. 还可以试试加一个updater

收到， 感谢你的建议，我下个版本添加上 😁

**Comment by Borber** [comment]
0.1.13 已经添加版本号显示和更新检测功能

**Comment by Borber** [comment]
那我这边先关掉issue喽，有其他的问题也欢迎反馈
