### ISSUE TITLE
开机启动

### ISSUE THREAD

**Issue by jlduu** [Borber/Tran#68]
建议在设置增加开机启动选项

**Comment by Borber** [comment]
其实比较建议自己添加到系统启动项🤣， 干净整洁，每个系统都有很简单的办法， 搜索一下

**Comment by Borber** [comment]
v.0.2.7 已添加开机启动, 🎉
![image](https://github.com/Borber/Tran/assets/30563826/f48f8b70-56a0-4840-bf4a-5c68c783bdb0)
