### ISSUE TITLE
0.2.1 无法使用

### ISSUE THREAD

**Issue by qiang-yu** [Borber/Tran#72]
系统 : Win 10 x64 

我下载的是 0.2.1 portable windows 版本

启动程序，在右下角 Tray 有图标，然后 ... 就没有然后了

1. 双击右下角图标，没有任何反映，猜测程序是没有做图形界面，所以双击没有界面
2. 右键 Tray 的图标，选择 Mirror/Google，切换多次，菜单不会显示打钩，猜测可能没做打钩显示
3. 浏览器鼠标选中一段英文，没有任何反映，猜测不会自动取词
4. 双击 Caps Lock ，没反应
5. 按 Alt + X ，没反应
6. 不知道该怎么用这个程序了，没界面，也没说明

另外，猜测，是不是必须要 Administrator 权限？ 
我 Win 10 是普通用户，不是 Administrator，猜测或许可能有这个原因？ 没看到有说明

测试，右键，用管理员权限运行，结果和上面一样

最后下载了 0.13 试了一下，双击启动，右下角 Tray 出现图标，然后 .... 图标就消失了，猜测是程序直接 Segment Fault 了？

**Comment by Borber** [comment]
![image](https://github.com/Borber/Tran/assets/30563826/c785e43f-1143-4abc-b208-5778949eeb00)

1. 左键确实没有界面 正常
2. 右键没有做打勾     正常
3. 选中无反应            正常
4. 双击 Caps Lock ，没反应   你选中了文本吗?
5.  Alt + X没反应      正常     因为删除了这个快捷键
6. 宝, 说明在这儿 
![image](https://github.com/Borber/Tran/assets/30563826/8e357bf9-e9c3-4bb2-b9a0-47ed13df39ea)

**Comment by Borber** [comment]
以及 你系统有安装 webwiew嘛? 没有的话请使用 msi 安装哦

**Comment by Borber** [comment]
没问题的话我就先 close 这个 issue喽, 有的话欢迎继续提问
