### ISSUE TITLE
求一个便携版~

### ISSUE THREAD

**Issue by LJason77** [Borber/tran#8]
就是：
- 不需要安装，解压就能使用；
- 所有数据都在这个目录下；
- 可以随便移动目录

**Comment by Borber** [comment]
尝试一下： https://github.com/Borber/tran/releases/tag/v.0.1.5

**Comment by LJason77** [comment]
![image](https://github.com/Borber/tran/assets/11374869/761cb51c-2189-4a5f-9895-8fad96204c64)
显示一次后会长时间显示这个框，什么操作都没反应。
取消划词、点击两个按钮、取消焦点都没反应，框也不消失，像是冻结了。

解决方式是重新划词，再多按几次快捷键。

我又多试了几次，冻结还是偶发性的。

**Comment by Borber** [comment]
> ![image](https://private-user-images.githubusercontent.com/11374869/286869732-761cb51c-2189-4a5f-9895-8fad96204c64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzU0OTAsIm5iZiI6MTcwMTMzNTE5MCwicGF0aCI6Ii8xMTM3NDg2OS8yODY4Njk3MzItNzYxY2I1MWMtMjE4OS00YTVmLTk4OTUtOGZhZDk2MjA0YzY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA5MDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljMDU0NDI1NmM1NTM5YmZmMWVlY2M4YTlhYmJiZTcxN2YyMmI0ZWQ2YTA1MTU2NTZkNGYxNzc1NzFhYzgzMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.69xPFz6RyNVkKKbRMZ5Ahy4huhMaLG0OB_DDaD4xlG0) 显示一次后会长时间显示这个框，什么操作都没反应。 取消划词、点击两个按钮、取消焦点都没反应，框也不消失，像是冻结了。
> 
> 解决方式是重新划词，再多按几次快捷键。
> 
> 我又多试了几次，冻结还是偶发性的。

![image](https://github.com/Borber/tran/assets/30563826/d73e97a6-0047-4118-94b2-6446e366a422)
固定之后 点击这个试试， 因为划过 左边就固定了，

**Comment by LJason77** [comment]
根据首页的动图，我理解了划过就固定了，所以才会说 “点击两个按钮”。
冻结时两个按钮都没有反应。

不过冻结频率还是挺低的，实际测试下来，只要连续在用，多按几次快捷键，冻结就几乎不影响。

**Comment by Borber** [comment]
> 根据首页的动图，我理解了划过就固定了，所以才会说 “点击两个按钮”。 冻结时两个按钮都没有反应。
> 
> 不过冻结频率还是挺低的，实际测试下来，只要连续在用，多按几次快捷键，冻结就几乎不影响。

按理来说 UI 和很多请求都是异步的，不大可能冻结在某个地方无响应， 我后面添加一些 log 来方便定位错误， 顺便问一下，你用的是镜像模式还是？

**Comment by LJason77** [comment]
我看到有代理的选项，就直接走代理了

**Comment by Borber** [comment]
> 我看到有代理的选项，就直接走代理了

有没有可能是代理的问题， 你试试镜像模式？可能会稍微慢一点点

**Comment by Borber** [comment]
有可能你那个显示空白是因为请求错误导致的， 错误处理我这边还没彻底覆盖掉

**Comment by LJason77** [comment]
> 有没有可能是代理的问题， 你试试镜像模式？可能会稍微慢一点点

这个我测试过了，代理立刻出现 translate.googleapis.com 的访问日志。按几次快捷键，就有几次访问日志。

总结一个可能出现冻结的操作顺序：

1. 划词，按快捷键，出现窗口。（这时候软件有可能会失去焦点）
2. 这时候如果再按一次快捷键，窗口会空白，如果在之前就已经固定，则有概率会冻结，两个按钮都没有反应。
3. 重新划词，并且多按几次快捷键可以恢复。

**Comment by Borber** [comment]
> > 有没有可能是代理的问题， 你试试镜像模式？可能会稍微慢一点点
> 
> 这个我测试过了，代理立刻出现 translate.googleapis.com 的访问日志。按几次快捷键，就有几次访问日志。
> 
> 总结一个可能出现冻结的操作顺序：
> 
> 1. 划词，按快捷键，出现窗口。（这时候软件有可能会失去焦点）
> 2. 这时候如果再按一次快捷键，窗口会空白，如果在之前就已经固定，则有概率会冻结，两个按钮都没有反应。
> 3. 重新划词，并且多按几次快捷键可以恢复。

已经复现， 我将寻找解决办法， 感谢

**Comment by Borber** [comment]
只复现出来了一次。。。 我稍微加了一点修复，发了  0.1.6

**Comment by LJason77** [comment]
不会冻结了。

---

另外，如果能改字体大小就好了。

**Comment by LJason77** [comment]
好的，我没有其他问题了。

**Comment by Borber** [comment]
> 好的，我没有其他问题了。

0.1.7 将调大默认字体
