### ISSUE TITLE
怎么弹出翻译界面

### ISSUE THREAD

**Issue by zrz4066** [Borber/Tran#88]
怎么弹出翻译界面？
![1708392352077](https://github.com/Borber/Tran/assets/16775484/dd8a8d76-2fb9-4d67-93ad-867f378be7ab)

![image](https://github.com/Borber/Tran/assets/16775484/778dc264-3225-4641-b9f6-31e1ce6a5c96)

**Comment by Borber** [comment]
> 怎么弹出翻译界面？ ![1708392352077](https://private-user-images.githubusercontent.com/16775484/306105889-dd8a8d76-2fb9-4d67-93ad-867f378be7ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzOTI5NDAsIm5iZiI6MTcwODM5MjY0MCwicGF0aCI6Ii8xNjc3NTQ4NC8zMDYxMDU4ODktZGQ4YThkNzYtMmZiOS00ZDY3LTkzYWQtODY3ZjM3OGJlN2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDAxMzA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMGY1MDc5MDdlNjRkNDdkZGY2MDU3MjZlZDlhYmNlNDc4N2U3MzZiMjZkYmViMzRmMTg0YWZmNTZmZTAxNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RA5RxE-tXs0CK4iimYRG7q5CYvK7NYqzR3qeqh0fJ1U)
> 
> ![image](https://private-user-images.githubusercontent.com/16775484/306105949-778dc264-3225-4641-b9f6-31e1ce6a5c96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzOTI5NDAsIm5iZiI6MTcwODM5MjY0MCwicGF0aCI6Ii8xNjc3NTQ4NC8zMDYxMDU5NDktNzc4ZGMyNjQtMzIyNS00NjQxLWI5ZjYtMzFlMWNlNmE1Yzk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDAxMzA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiOWFiYzA3NDMzMmUxMWM4MjYyZTcxNDI5Y2Q5OGVmZjI3NjBhODI1ODIzNjY4YmNkMDQ3MDg0OTFmZTEzYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1z-ts3Grfghy9mFD2r3vzXhByiV9J_x1q_75pe2gXyM)

建议选 mirror哈， 以及 使用方法是： 选中一段文本 然后双击  大写锁定键 `CapsLock`

**Comment by Borber** [comment]
你好呀， 请问你的问题解决了吗？

**Comment by zrz4066** [comment]
之前没注意使用方法，现在好了。谢谢

**Comment by Timmytimi** [comment]
可以自定义快捷键吗?
