### ISSUE TITLE
双屏兼容问题

### ISSUE THREAD

**Issue by Cranberrycrisp** [Borber/Tran#96]
描述：在副屏使用时弹框不会跟随，只出现在主屏区域的同一水平线上。

试用了一下，我的显示器左右排列，副屏低主屏高，副屏翻译弹框可能会出现在主屏的屏幕外。

环境：Win10/Tran 0.2.4/Tran_zh_en_windows_portable.exe

**Comment by Borber** [comment]
咦， 理论上来说不会啊， 我以前专门适配过双屏来着，我稍晚一点时间再去测试一下

**Comment by Borber** [comment]
检测出来了， 副屏幕放到左侧确实会出问题， 我去修改一下试试

**Comment by Borber** [comment]
已修复，等待 0.2.5 版本编译完成即可使用

**Comment by Borber** [comment]
https://github.com/Borber/Tran/releases/tag/v.0.2.5 请尝试0.2.5版本

**Comment by Borber** [comment]
没问题我就先close喽
